"""PC/SC constants shared by the ctypes binding, the simulator and the CLI.

Values follow winscard.h / pcsclite.h.  Where Windows and pcsc-lite differ
(SCARD_PROTOCOL_RAW, SCARD_CTL_CODE) the platform specific value is chosen
at import time.
"""

from __future__ import annotations

import sys

IS_WINDOWS = sys.platform.startswith("win")
IS_MACOS = sys.platform == "darwin"

# --- scopes ---------------------------------------------------------------
SCARD_SCOPE_USER = 0
SCARD_SCOPE_TERMINAL = 1
SCARD_SCOPE_SYSTEM = 2

# --- share modes ----------------------------------------------------------
SCARD_SHARE_EXCLUSIVE = 1
SCARD_SHARE_SHARED = 2
SCARD_SHARE_DIRECT = 3

# --- protocols ------------------------------------------------------------
SCARD_PROTOCOL_UNDEFINED = 0x0000
SCARD_PROTOCOL_T0 = 0x0001
SCARD_PROTOCOL_T1 = 0x0002
SCARD_PROTOCOL_RAW = 0x10000 if IS_WINDOWS else 0x0004
SCARD_PROTOCOL_T15 = 0x0008
SCARD_PROTOCOL_ANY = SCARD_PROTOCOL_T0 | SCARD_PROTOCOL_T1

PROTOCOL_NAMES = {
    SCARD_PROTOCOL_UNDEFINED: "undefined",
    SCARD_PROTOCOL_T0: "T=0",
    SCARD_PROTOCOL_T1: "T=1",
    SCARD_PROTOCOL_RAW: "RAW",
    SCARD_PROTOCOL_T15: "T=15",
}

# --- dispositions ---------------------------------------------------------
SCARD_LEAVE_CARD = 0
SCARD_RESET_CARD = 1
SCARD_UNPOWER_CARD = 2
SCARD_EJECT_CARD = 3

# --- SCardGetStatusChange reader states -----------------------------------
SCARD_STATE_UNAWARE = 0x0000
SCARD_STATE_IGNORE = 0x0001
SCARD_STATE_CHANGED = 0x0002
SCARD_STATE_UNKNOWN = 0x0004
SCARD_STATE_UNAVAILABLE = 0x0008
SCARD_STATE_EMPTY = 0x0010
SCARD_STATE_PRESENT = 0x0020
SCARD_STATE_ATRMATCH = 0x0040
SCARD_STATE_EXCLUSIVE = 0x0080
SCARD_STATE_INUSE = 0x0100
SCARD_STATE_MUTE = 0x0200
SCARD_STATE_UNPOWERED = 0x0400

# --- SCardStatus card states ----------------------------------------------
SCARD_UNKNOWN = 0x0001
SCARD_ABSENT = 0x0002
SCARD_PRESENT = 0x0004
SCARD_SWALLOWED = 0x0008
SCARD_POWERED = 0x0010
SCARD_NEGOTIABLE = 0x0020
SCARD_SPECIFIC = 0x0040

INFINITE = 0xFFFFFFFF
MAX_ATR_SIZE = 36 if IS_WINDOWS else 33
MAX_BUFFER_SIZE_EXTENDED = 65548


def SCARD_CTL_CODE(code: int) -> int:
    """Build a control code for SCardControl (platform dependent encoding)."""
    if IS_WINDOWS:
        # CTL_CODE(FILE_DEVICE_SMARTCARD, code, METHOD_BUFFERED, FILE_ANY_ACCESS)
        return (0x31 << 16) | (code << 2)
    return 0x42000000 + code


# Control codes used with OMNIKEY readers (see HID PLT-03099 and the
# hidglobal/HID-OMNIKEY-Sample-Codes repository).
CM_IOCTL_GET_FW_VERSION = SCARD_CTL_CODE(3001)       # legacy OMNIKEY driver
CM_IOCTL_GET_FEATURE_REQUEST = SCARD_CTL_CODE(3400)  # PC/SC part 10
IOCTL_CCID_ESCAPE = SCARD_CTL_CODE(3500)             # CCID escape (vendor payload)

# PC/SC part 10 feature tags returned by CM_IOCTL_GET_FEATURE_REQUEST.
FEATURE_NAMES = {
    0x01: "FEATURE_VERIFY_PIN_START",
    0x02: "FEATURE_VERIFY_PIN_FINISH",
    0x03: "FEATURE_MODIFY_PIN_START",
    0x04: "FEATURE_MODIFY_PIN_FINISH",
    0x05: "FEATURE_GET_KEY_PRESSED",
    0x06: "FEATURE_VERIFY_PIN_DIRECT",
    0x07: "FEATURE_MODIFY_PIN_DIRECT",
    0x08: "FEATURE_MCT_READER_DIRECT",
    0x09: "FEATURE_MCT_UNIVERSAL",
    0x0A: "FEATURE_IFD_PIN_PROPERTIES",
    0x0B: "FEATURE_ABORT",
    0x0C: "FEATURE_SET_SPE_MESSAGE",
    0x0D: "FEATURE_VERIFY_PIN_DIRECT_APP_ID",
    0x0E: "FEATURE_MODIFY_PIN_DIRECT_APP_ID",
    0x0F: "FEATURE_WRITE_DISPLAY",
    0x10: "FEATURE_GET_KEY",
    0x11: "FEATURE_IFD_DISPLAY_PROPERTIES",
    0x12: "FEATURE_GET_TLV_PROPERTIES",
    0x13: "FEATURE_CCID_ESC_COMMAND",
    0x14: "FEATURE_EXECUTE_PACE",
}
FEATURE_CCID_ESC_COMMAND = 0x13
FEATURE_GET_TLV_PROPERTIES = 0x12


def SCARD_ATTR_VALUE(cls: int, tag: int) -> int:
    return (cls << 16) | tag


SCARD_CLASS_VENDOR_INFO = 1
SCARD_CLASS_COMMUNICATIONS = 2
SCARD_CLASS_PROTOCOL = 3
SCARD_CLASS_POWER_MGMT = 4
SCARD_CLASS_SECURITY = 5
SCARD_CLASS_MECHANICAL = 6
SCARD_CLASS_VENDOR_DEFINED = 7
SCARD_CLASS_IFD_PROTOCOL = 8
SCARD_CLASS_ICC_STATE = 9
SCARD_CLASS_SYSTEM = 0x7FFF

SCARD_ATTR_VENDOR_NAME = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_INFO, 0x0100)
SCARD_ATTR_VENDOR_IFD_TYPE = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_INFO, 0x0101)
SCARD_ATTR_VENDOR_IFD_VERSION = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_INFO, 0x0102)
SCARD_ATTR_VENDOR_IFD_SERIAL_NO = SCARD_ATTR_VALUE(SCARD_CLASS_VENDOR_INFO, 0x0103)
SCARD_ATTR_CHANNEL_ID = SCARD_ATTR_VALUE(SCARD_CLASS_COMMUNICATIONS, 0x0110)
SCARD_ATTR_PROTOCOL_TYPES = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0120)
SCARD_ATTR_DEFAULT_CLK = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0121)
SCARD_ATTR_MAX_CLK = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0122)
SCARD_ATTR_DEFAULT_DATA_RATE = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0123)
SCARD_ATTR_MAX_DATA_RATE = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0124)
SCARD_ATTR_MAX_IFSD = SCARD_ATTR_VALUE(SCARD_CLASS_PROTOCOL, 0x0125)
SCARD_ATTR_POWER_MGMT_SUPPORT = SCARD_ATTR_VALUE(SCARD_CLASS_POWER_MGMT, 0x0131)
SCARD_ATTR_CHARACTERISTICS = SCARD_ATTR_VALUE(SCARD_CLASS_MECHANICAL, 0x0150)
SCARD_ATTR_CURRENT_PROTOCOL_TYPE = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0201)
SCARD_ATTR_CURRENT_CLK = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0202)
SCARD_ATTR_CURRENT_F = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0203)
SCARD_ATTR_CURRENT_D = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0204)
SCARD_ATTR_CURRENT_N = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0205)
SCARD_ATTR_CURRENT_W = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0206)
SCARD_ATTR_CURRENT_IFSC = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0207)
SCARD_ATTR_CURRENT_IFSD = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0208)
SCARD_ATTR_CURRENT_BWT = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x0209)
SCARD_ATTR_CURRENT_CWT = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x020A)
SCARD_ATTR_CURRENT_EBC_ENCODING = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x020B)
SCARD_ATTR_EXTENDED_BWT = SCARD_ATTR_VALUE(SCARD_CLASS_IFD_PROTOCOL, 0x020C)
SCARD_ATTR_ICC_PRESENCE = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0300)
SCARD_ATTR_ICC_INTERFACE_STATUS = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0301)
SCARD_ATTR_CURRENT_IO_STATE = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0302)
SCARD_ATTR_ATR_STRING = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0303)
SCARD_ATTR_ICC_TYPE_PER_ATR = SCARD_ATTR_VALUE(SCARD_CLASS_ICC_STATE, 0x0304)
SCARD_ATTR_DEVICE_UNIT = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0001)
SCARD_ATTR_DEVICE_IN_USE = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0002)
SCARD_ATTR_DEVICE_FRIENDLY_NAME = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0003)
SCARD_ATTR_DEVICE_SYSTEM_NAME = SCARD_ATTR_VALUE(SCARD_CLASS_SYSTEM, 0x0004)

ATTRIBUTE_NAMES = {
    SCARD_ATTR_VENDOR_NAME: "VENDOR_NAME",
    SCARD_ATTR_VENDOR_IFD_TYPE: "VENDOR_IFD_TYPE",
    SCARD_ATTR_VENDOR_IFD_VERSION: "VENDOR_IFD_VERSION",
    SCARD_ATTR_VENDOR_IFD_SERIAL_NO: "VENDOR_IFD_SERIAL_NO",
    SCARD_ATTR_CHANNEL_ID: "CHANNEL_ID",
    SCARD_ATTR_PROTOCOL_TYPES: "PROTOCOL_TYPES",
    SCARD_ATTR_DEFAULT_CLK: "DEFAULT_CLK",
    SCARD_ATTR_MAX_CLK: "MAX_CLK",
    SCARD_ATTR_DEFAULT_DATA_RATE: "DEFAULT_DATA_RATE",
    SCARD_ATTR_MAX_DATA_RATE: "MAX_DATA_RATE",
    SCARD_ATTR_MAX_IFSD: "MAX_IFSD",
    SCARD_ATTR_CHARACTERISTICS: "CHARACTERISTICS",
    SCARD_ATTR_CURRENT_PROTOCOL_TYPE: "CURRENT_PROTOCOL_TYPE",
    SCARD_ATTR_CURRENT_CLK: "CURRENT_CLK",
    SCARD_ATTR_CURRENT_F: "CURRENT_F",
    SCARD_ATTR_CURRENT_D: "CURRENT_D",
    SCARD_ATTR_CURRENT_IFSC: "CURRENT_IFSC",
    SCARD_ATTR_CURRENT_IFSD: "CURRENT_IFSD",
    SCARD_ATTR_CURRENT_BWT: "CURRENT_BWT",
    SCARD_ATTR_CURRENT_CWT: "CURRENT_CWT",
    SCARD_ATTR_ICC_PRESENCE: "ICC_PRESENCE",
    SCARD_ATTR_ICC_INTERFACE_STATUS: "ICC_INTERFACE_STATUS",
    SCARD_ATTR_ATR_STRING: "ATR_STRING",
    SCARD_ATTR_ICC_TYPE_PER_ATR: "ICC_TYPE_PER_ATR",
    SCARD_ATTR_DEVICE_UNIT: "DEVICE_UNIT",
    SCARD_ATTR_DEVICE_IN_USE: "DEVICE_IN_USE",
    SCARD_ATTR_DEVICE_FRIENDLY_NAME: "DEVICE_FRIENDLY_NAME",
    SCARD_ATTR_DEVICE_SYSTEM_NAME: "DEVICE_SYSTEM_NAME",
}

# --- return codes ---------------------------------------------------------
SCARD_S_SUCCESS = 0x00000000
SCARD_E_NO_SMARTCARD = 0x8010000C
SCARD_E_TIMEOUT = 0x8010000A
SCARD_E_CANCELLED = 0x80100002
SCARD_E_NO_SERVICE = 0x8010001D
SCARD_E_NO_READERS_AVAILABLE = 0x8010002E
SCARD_E_UNKNOWN_READER = 0x80100009
SCARD_E_SHARING_VIOLATION = 0x8010000B
SCARD_E_READER_UNAVAILABLE = 0x80100017
SCARD_W_REMOVED_CARD = 0x80100069
SCARD_W_RESET_CARD = 0x80100068
SCARD_W_UNRESPONSIVE_CARD = 0x80100066
SCARD_W_UNPOWERED_CARD = 0x80100067
SCARD_E_INSUFFICIENT_BUFFER = 0x80100008
SCARD_E_NOT_TRANSACTED = 0x80100016
SCARD_E_PROTO_MISMATCH = 0x8010000F
SCARD_E_UNSUPPORTED_FEATURE = 0x80100022

ERROR_NAMES = {
    0x00000000: "SCARD_S_SUCCESS",
    0x80100001: "SCARD_F_INTERNAL_ERROR",
    0x80100002: "SCARD_E_CANCELLED",
    0x80100003: "SCARD_E_INVALID_HANDLE",
    0x80100004: "SCARD_E_INVALID_PARAMETER",
    0x80100005: "SCARD_E_INVALID_TARGET",
    0x80100006: "SCARD_E_NO_MEMORY",
    0x80100007: "SCARD_F_WAITED_TOO_LONG",
    0x80100008: "SCARD_E_INSUFFICIENT_BUFFER",
    0x80100009: "SCARD_E_UNKNOWN_READER",
    0x8010000A: "SCARD_E_TIMEOUT",
    0x8010000B: "SCARD_E_SHARING_VIOLATION",
    0x8010000C: "SCARD_E_NO_SMARTCARD",
    0x8010000D: "SCARD_E_UNKNOWN_CARD",
    0x8010000E: "SCARD_E_CANT_DISPOSE",
    0x8010000F: "SCARD_E_PROTO_MISMATCH",
    0x80100010: "SCARD_E_NOT_READY",
    0x80100011: "SCARD_E_INVALID_VALUE",
    0x80100012: "SCARD_E_SYSTEM_CANCELLED",
    0x80100013: "SCARD_F_COMM_ERROR",
    0x80100014: "SCARD_F_UNKNOWN_ERROR",
    0x80100015: "SCARD_E_INVALID_ATR",
    0x80100016: "SCARD_E_NOT_TRANSACTED",
    0x80100017: "SCARD_E_READER_UNAVAILABLE",
    0x80100018: "SCARD_P_SHUTDOWN",
    0x80100019: "SCARD_E_PCI_TOO_SMALL",
    0x8010001A: "SCARD_E_READER_UNSUPPORTED",
    0x8010001B: "SCARD_E_DUPLICATE_READER",
    0x8010001C: "SCARD_E_CARD_UNSUPPORTED",
    0x8010001D: "SCARD_E_NO_SERVICE",
    0x8010001E: "SCARD_E_SERVICE_STOPPED",
    0x8010001F: "SCARD_E_UNEXPECTED",
    0x80100020: "SCARD_E_ICC_INSTALLATION",
    0x80100021: "SCARD_E_ICC_CREATEORDER",
    0x80100022: "SCARD_E_UNSUPPORTED_FEATURE",
    0x80100023: "SCARD_E_DIR_NOT_FOUND",
    0x80100024: "SCARD_E_FILE_NOT_FOUND",
    0x80100025: "SCARD_E_NO_DIR",
    0x80100026: "SCARD_E_NO_FILE",
    0x80100027: "SCARD_E_NO_ACCESS",
    0x80100028: "SCARD_E_WRITE_TOO_MANY",
    0x80100029: "SCARD_E_BAD_SEEK",
    0x8010002A: "SCARD_E_INVALID_CHV",
    0x8010002B: "SCARD_E_UNKNOWN_RES_MNG",
    0x8010002C: "SCARD_E_NO_SUCH_CERTIFICATE",
    0x8010002D: "SCARD_E_CERTIFICATE_UNAVAILABLE",
    0x8010002E: "SCARD_E_NO_READERS_AVAILABLE",
    0x8010002F: "SCARD_E_COMM_DATA_LOST",
    0x80100030: "SCARD_E_NO_KEY_CONTAINER",
    0x80100031: "SCARD_E_SERVER_TOO_BUSY",
    0x80100065: "SCARD_W_UNSUPPORTED_CARD",
    0x80100066: "SCARD_W_UNRESPONSIVE_CARD",
    0x80100067: "SCARD_W_UNPOWERED_CARD",
    0x80100068: "SCARD_W_RESET_CARD",
    0x80100069: "SCARD_W_REMOVED_CARD",
    0x8010006A: "SCARD_W_SECURITY_VIOLATION",
    0x8010006B: "SCARD_W_WRONG_CHV",
    0x8010006C: "SCARD_W_CHV_BLOCKED",
    0x8010006D: "SCARD_W_EOF",
    0x8010006E: "SCARD_W_CANCELLED_BY_USER",
    0x8010006F: "SCARD_W_CARD_NOT_AUTHENTICATED",
}
